x-ti-template: &ti
  image: ghcr.io/thingsdb/node
  restart: unless-stopped
  environment:
    - THINGSDB_BIND_CLIENT_ADDR = '::'
    - THINGSDB_BIND_NODE_ADDR = '::'
    - THINGSDB_HTTP_API_PORT = 9210
    - THINGSDB_HTTP_STATUS_PORT = 8080
    - THINGSDB_MODULES_PATH = /modules/
    - THINGSDB_STORAGE_PATH = /data/

services:
  node0:
    << : *ti
    hostname: node0
    container_name: node0
    command: "--init"
    ports:
      - 9200:9200
      - 9210:9210
      - 8080:8080
    volumes:
      - ./node0/data:/data/
      - ./node0/modules:/modules/
      - ./node0/dump:/dump/

  # node1:
  #   << : *ti
  #   hostname: node1
  #   container_name: node1
  #   command: "--secret pass"
  #   ports:
  #     - 8081:8080
  #   volumes:
  #     - ./node1/data:/data/
  #     - ./node1/modules:/modules/
  #     - ./node1/dump:/dump/
  # node2:
  #   << : *ti
  #   hostname: node2
  #   container_name: node2
  #   command: "--secret pass"
  #   ports:
  #     - 8082:8080
  #   volumes:
  #     - ./node2/data:/data/
  #     - ./node2/modules:/modules/
  #     - ./node2/dump:/dump/
